config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens

  # Defines the root path route ("/")
  # root "articles#index"
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new kitten_params

    if @kitten.save
      redirect_to @kitten, notice: 'Kitten created successfully'
    else
      render :new, status: :unprocessable_entity, alert: 'Kitten not created'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: 'Kitten updated successfully'
    else
      render :edit, status: :unprocessable_entity, alert: 'Kitten not updated'
    end
  end

  def destroy
    kitten = Kitten.find(params[:id])
    kitten.destroy

    redirect_to root_path, status: :see_other, notice: 'Kitten deleted successfully'
  end


  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :softness, :cuteness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_error_messages.html.erb
<% @kitten.errors.full_messages.each do |message| %>
  <div><%= message %></div>
<% end %>

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>

  <%= f.label :age %>
  <%= f.number_field :age %><br><br>

  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %><br><br>

  <%= f.label :softness %>
  <%= f.text_field :softness %><br><br>

  <%= f.submit %>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#delete</h1>
<p>Find me in app/views/kittens/delete.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Kittens#edit</h1>
<%= render 'error_messages' %>
<%= render partial: 'form', locals: {kitten: @kitten} %><br>
<%= button_to 'Delete kitten', kitten_path(@kitten), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

app/views/kittens/index.html.erb
<h1>Kittens#index</h1>
<% @kittens.each do |kitten| %>
  <%= link_to kitten_path(kitten) do %>
    <p><%= kitten.name %></p>
  <% end %>
<% end %>

app/views/kittens/new.html.erb
<h1>Kittens#new</h1>
<%= render 'error_messages' %>
<%= render partial: 'form', locals: {kitten: @kitten} %>

app/views/kittens/show.html.erb
<h1>Kittens#show</h1>
<div>
  <p>Name: <%= @kitten.name %></p>
  <p>Age: <%= @kitten.age %></p>
  <p>Cuteness: <%= @kitten.cuteness %></p>
  <p>Softness: <%= @kitten.softness %></p>
  <%= button_to 'Delete kitten', kitten_path(@kitten), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
</div>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKitten</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>